---

- name: Create /usr/share/java directory
  file:
    path: /usr/share/java
    state: directory
    mode: 0755

- name: Get mysql connector file status
  stat:
    path: /usr/share/java/mysql-connector-java.jar
  register: mysql_connector_java

- name: Copy MySQL Connector/J
  copy:
    src: "{{ mysql.path.pkgs_connector }}"
    dest: "{{ common.path.temp_install }}/mysql-connector-java.zip"
  when: not mysql_connector_java.stat.exists

- name: Extract MySQL Connector/J zip file
  unarchive:
    src: "{{ common.path.temp_install }}/mysql-connector-java.zip"
    dest: "{{ common.path.temp_install }}"
    copy: no
  when: not mysql_connector_java.stat.exists

- name: Copy MySQL Connector/J jar file to correct location
  copy:
    src: "{{ common.path.temp_install }}/mysql-connector-java-5.1.48/mysql-connector-java-5.1.48.jar"
    dest: /usr/share/java/mysql-connector-java.jar
    mode: 0644
    remote_src: yes
  when: not mysql_connector_java.stat.exists
