---

# - name: Update Cloudera Manager settings
#   uri:
#     url: "{{ cm_api_url }}/cm/config"
#     method: PUT
#     body_format: json
#     body: "{{ lookup('template', 'scm.j2', convert_data=False) }}"
#     status_code: "200"
#     force_basic_auth: yes
#     user: "{{ scm_default_user }}"
#     password: "{{ scm_default_pass }}"
#     return_content: yes
#   register: scm_resp

# - name: Show parcels setting resp
#   debug:
#     var: scm_resp
#     verbosity: 1

- name: Create parcel directory
  file:
    path: /opt/cloudera/parcel-repo
    state: directory
    owner: cloudera-scm
    group: cloudera-scm
    mode: 0755

- name: Copy parcels to scm directory
  copy:
    src: "{{ item }}"
    dest: /opt/cloudera/parcel-repo/
  with_items: "{{ cloudera.parcels }}"
  notify:
    - Restart cloudera-scm-server
